---
name: Build Docker Image


on:
  workflow_call:
    secrets:
      dockerhub-token:
        description: 'Token for dockerhub'
        required: true

env:
  REPO_NAME: yaakxis
  IMAGE_NAME: experimentga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yaakxis
          password: ${{ secrets.dockerhub-token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest