---
name: Run Pytest

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version we want to lint by"
        required: true
        type: number
        default: 3.9

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install flake8
        run: pip install flake8
        shell: bash
        
      - name: Run flake8
        run: flake8 .
        shell: bash
