# CircleCI configuration file
version: 2.1

# Define reusable commands
commands:
  checkout_and_setup_python:
    parameters:
      python-version:
        type: string
        default: "3.9"
    steps:
      - checkout
      - setup-python:
          version: << parameters.python-version >>
  install_flake8:
    steps:
      - run: pip install flake8
  install_dependencies:
    steps:
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  install_pytest:
    steps:
      - run: pip install pytest
  login_to_docker_hub:
    steps:
      - run: echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login --username $DOCKER_HUB_USERNAME --password-stdin

# Define reusable executors
executors:
  ubuntu-latest:
    docker:
      - image: cimg/base:2022.05

# Define jobs
jobs:
  lint:
    executor: ubuntu-latest
    steps:
      - checkout_and_setup_python
      - install_flake8
      - run: flake8 .
  test:
    executor: ubuntu-latest
    steps:
      - checkout_and_setup_python
      - install_dependencies
      - install_pytest
      - run: pytest
  build:
    executor: ubuntu-latest
    steps:
      - checkout_and_setup_python
      - setup_remote_docker # Enable Docker commands in the job
      - login_to_docker_hub
      - run: docker build --tag $IMAGE_NAME:latest .
      - run: docker push $IMAGE_NAME:latest

# Define workflows
workflows:
  ci:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test

