# CircleCI configuration file
version: 2.1

# Define reusable commands
commands:
  install_flake8:
    steps:
      - run: pip install flake8
  install_dependencies:
    steps:
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  install_pytest:
    steps:
      - run: pip install pytest
  login_to_docker_hub:
    steps:
      - run: docker login --username yaakxis --password $DOCKERHUB_TOKEN

# Define reusable executors
executors:
  ubuntu-latest:
    docker:
      - image: cimg/python:3.9

# Define jobs
jobs:
  lint:
    executor: ubuntu-latest
    steps:
      - checkout
      - install_flake8
      - run: flake8 .
  test:
    executor: ubuntu-latest
    steps:
      - checkout
      - install_dependencies
      - install_pytest
      - run: pytest
  build:
    executor: ubuntu-latest
    environment:
      IMAGE_NAME: "experiment-cci"
    steps:
      - checkout
      - setup_remote_docker # Enable Docker commands in the job
      - login_to_docker_hub
      - run: echo "Image name is ${IMAGE_NAME}"
      - run: docker build --tag $IMAGE_NAME:latest .
      - run: docker push $IMAGE_NAME:latest

# Define workflows
workflows:
  ci:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
          context: YaakXis # Specify the context at the workflow level
