---
name: CI
on:
  pull_request:
    types:
      - synchronize
env:
  IMAGE_NAME: experimentga

jobs:
  lint:
    uses: ./.github/workflows/python-lint.yml
    
  test:
    needs: lint
    uses: ./.github/workflows/integration.yml

  build:
    needs: test
    uses: ./.github/workflows/docker-build.yml
    secrets:
      dockerhub-token: ${{ secrets.YAAKXIS_DOCKER_TOKEN }}
