---
name: CI
on:
  pull_request:
    types:
      - synchronize
env:
  IMAGE_NAME: experimentga

jobs:
  lint:
    uses: ./.github/workflows/python-lint.yml
    
  test:
    needs: lint
    uses: ./.github/workflows/integration.yml

  build:
    needs: test
    runs-on: ubuntu-latest
    # uses: ./.github/workflows/docker-build.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yaakxis
          password: ${{ secrets.YAAKXIS_DOCKER_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
