---
name: CI
on:
  pull_request:
    types:
      - synchronize
env:
  IMAGE_NAME: experimentga

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/python-lint.yml
        with:
          python-version: 3.9
    
  test:
    needs: lint
    uses: ./.github/workflows/integration.yml

  build:
    needs: test
    uses: ./.github/workflows/docker-build.yml
    secrets:
      dockerhub-token: ${{ secrets.YAAKXIS_DOCKER_TOKEN }}
