---
name: On Merge
on:
  push:
    branches:
      - main
      - master
      - prod
      - release
      - dev
      - demo
env:
  IMAGE_NAME: experimentga

jobs:
  pr:
    uses: ./.github/workflows/pr.yml

  build:
    needs: test
    uses: ./.github/workflows/jobs/docker-build.yml
    secrets:
      dockerhub-token: ${{ secrets.YAAKXIS_DOCKER_TOKEN }}
