---
name: PR
on:
  workflow_call:
  pull_request:
    types:
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/jobs/python-lint
        with:
          python-version: 3.9
    
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/get-pytest
        with:
          python-version: 3.9
      - name: Run pytest
        run: pytest
